# -*- coding: utf-8 -*-
"""
scripts/generate_clothing_512d_notebook.py
===========================================
Tạo notebook chuyên biệt chạy STAIR Baseline trên Clothing ở không gian 512 chiều (512D):
notebook/stair_clothing_512d.ipynb
- Thực thi: STAIR Baseline (Embedding Dim = 512D, kNN = 5-1, Batch = 2048, Patience = 30)
- Đối sánh trực tiếp 3 mô hình:
  1. STAIR Baseline (64D)  : NDCG@20 = 0.0398 [@Ep205]
  2. STAIR Baseline (512D) : Kết quả vừa huấn luyện
  3. STAIR DCD-Gated (512D): NDCG@20 = 0.0431 [@Ep30] (+8.08%)
"""
import json
import os

with open(r"d:\STAIR-Enhanced\models\stair_breakthrough.py", "r", encoding="utf-8") as f:
    breakthrough_model_code = f.read()

with open(r"d:\STAIR-Enhanced\models\stair_ne_nlgcl_v5_plus.py", "r", encoding="utf-8") as f:
    v5_plus_model_code = f.read()

with open(r"d:\STAIR-Enhanced\main_stair_ne_nlgcl_v5_plus.py", "r", encoding="utf-8") as f:
    runner_code = f.read()

with open(r"d:\STAIR-Enhanced\main.py", "r", encoding="utf-8") as f:
    baseline_code = f.read()

with open(r"d:\STAIR-Enhanced\configs\Amazon2014Clothing_550_MMRec.yaml", "r", encoding="utf-8") as f:
    clothing_yaml_code = f.read()

template_path = r"d:\STAIR-Enhanced\notebook\stair_electronics.ipynb"
with open(template_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

for cell in nb["cells"]:
    if cell.get("cell_type") == "code":
        cell["outputs"] = []
        cell["execution_count"] = None

# Cell 0: Header
cell0_source = [
    "# 🚀 THỰC NGHIỆM ĐỐI CHỨNG: STAIR BASELINE TRÊN CLOTHING Ở KHÔNG GIAN 512 CHIỀU (512D)\n",
    "## 🏆 Amazon Clothing (39,387 Users, 23,033 Items, Độ thưa 99.97%) | Embedding Dim = 512D | Batch Size = 2048\n",
    "---\n",
    "### 🎯 MỤC TIÊU VÀ Ý NGHĨA KHOA HỌC:\n",
    "1. **Mục tiêu thực nghiệm:**\n",
    "   - Huấn luyện mô hình **STAIR Baseline gốc** khi mở rộng dung lượng biểu diễn lên **512 chiều** (`embedding_dim: 512`) trên tập dữ liệu Amazon Clothing.\n",
    "   - Giữ nguyên toàn bộ cấu hình chuẩn của tác giả: $L=3$, $k_t=5, k_v=1$, tối ưu AdamW (`lr: 1e-3`, `weight_decay: 0.1`).\n",
    "2. **Đối sánh đa chiều 3 mốc thực nghiệm trên Clothing:**\n",
    "   - **Mốc 1:** STAIR Baseline chuẩn 64 chiều (`64D`) -> NDCG@20 = 0.0398 [@Ep205].\n",
    "   - **Mốc 2:** STAIR Baseline mở rộng 512 chiều (`512D`) -> Khảo sát năng lực tự thân của Baseline khi tăng dung lượng chiều.\n",
    "   - **Mốc 3:** STAIR DCD-Gated cải tiến 512 chiều (`512D`) -> NDCG@20 = 0.0431 [@Ep30] (+8.08% so với Baseline 64D).\n",
    "3. **Câu hỏi nghiên cứu trả lời:**\n",
    "   - *Việc tăng số chiều lên 512D trong Baseline có giúp cải thiện hiệu năng không, hay gây overfitting trên đồ thị siêu thưa 99.97%?*\n",
    "   - *Mức nhảy vọt của DCD-Gated (512D) đến từ việc mở rộng số chiều hay thực sự đến từ cơ chế Đồng thuận Kép (Dual-Consensus) & Van an toàn Gating Residuals?*\n"
]

# Cell 1: Environment & Sync
cell1_source = [
    "# Cell 1: Môi trường, Dependencies & Đồng bộ STAIR-Enhanced\n",
    "import os, shutil, subprocess, sys\n",
    "\n",
    "STAIR_DIR = '/kaggle/working/STAIR-Enhanced'\n",
    "os.chdir('/kaggle/working')\n",
    "\n",
    "# 1. Luôn clone hoặc đồng bộ cưỡng bức repository mới nhất từ origin/main\n",
    "if os.path.exists(STAIR_DIR):\n",
    "    print(\"Thư mục STAIR-Enhanced đã tồn tại. Đang đồng bộ cưỡng bức mã nguồn mới nhất...\")\n",
    "    try:\n",
    "        subprocess.run(['git', '-C', STAIR_DIR, 'fetch', 'origin', 'main'], check=True)\n",
    "        subprocess.run(['git', '-C', STAIR_DIR, 'reset', '--hard', 'origin/main'], check=True)\n",
    "        print(\"✅ Đã reset về commit mới nhất của origin/main.\")\n",
    "    except Exception as e:\n",
    "        print(f\"Lỗi git fetch/reset ({e}), đang làm sạch và clone lại từ đầu...\")\n",
    "        shutil.rmtree(STAIR_DIR, ignore_errors=True)\n",
    "        subprocess.run([\n",
    "            'git', 'clone', '--depth', '1',\n",
    "            'https://github.com/HenryBui777/STAIR-Enhanced.git', STAIR_DIR\n",
    "        ], check=True)\n",
    "else:\n",
    "    print(\"Cloning STAIR-Enhanced repository (branch main)...\")\n",
    "    subprocess.run([\n",
    "        'git', 'clone', '--depth', '1',\n",
    "        'https://github.com/HenryBui777/STAIR-Enhanced.git', STAIR_DIR\n",
    "    ], check=True)\n",
    "\n",
    "for p in [STAIR_DIR, '/kaggle/working']:\n",
    "    if p not in sys.path:\n",
    "        sys.path.insert(0, p)\n",
    "\n",
    "if os.path.exists(STAIR_DIR):\n",
    "    os.chdir(STAIR_DIR)\n",
    "\n",
    "# Ghi đảm bảo module baseline, runner và config tồn tại trên đĩa\n",
    "os.makedirs(os.path.join(STAIR_DIR, 'models'), exist_ok=True)\n",
    "os.makedirs(os.path.join(STAIR_DIR, 'configs'), exist_ok=True)\n",
    "with open(os.path.join(STAIR_DIR, 'models', 'stair_breakthrough.py'), 'w', encoding='utf-8') as f:\n",
    f"    f.write({repr(breakthrough_model_code)})\n",
    "with open(os.path.join(STAIR_DIR, 'models', 'stair_ne_nlgcl_v5_plus.py'), 'w', encoding='utf-8') as f:\n",
    f"    f.write({repr(v5_plus_model_code)})\n",
    "with open(os.path.join(STAIR_DIR, 'main_stair_ne_nlgcl_v5_plus.py'), 'w', encoding='utf-8') as f:\n",
    f"    f.write({repr(runner_code)})\n",
    "with open(os.path.join(STAIR_DIR, 'main.py'), 'w', encoding='utf-8') as f:\n",
    f"    f.write({repr(baseline_code)})\n",
    "with open(os.path.join(STAIR_DIR, 'configs', 'Amazon2014Clothing_550_MMRec.yaml'), 'w', encoding='utf-8') as f:\n",
    f"    f.write({repr(clothing_yaml_code)})\n",
    "\n",
    "# 2. Cài đặt các gói phụ thuộc bắt buộc\n",
    "print(\"📦 Cài đặt dependencies (torchdata, torch_geometric, freerec, nvidia-ml-py, prettytable, scipy)...\")\n",
    "subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '--no-deps', 'torchdata==0.7.1'], check=False)\n",
    "subprocess.run([\n",
    "    sys.executable, '-m', 'pip', 'install', '-q',\n",
    "    'torch_geometric', 'freerec==0.8.5', 'nvidia-ml-py', 'prettytable', 'matplotlib', 'pyyaml', 'seaborn', 'scipy', 'pandas'\n",
    "], check=True)\n",
    "\n",
    "# 3. Kaggle TorchData compatibility shims cho FreeRec (PyTorch 2.x & Python 3.10+)\n",
    "import types\n",
    "import torch.utils.data\n",
    "\n",
    "try:\n",
    "    import torchdata\n",
    "    import torchdata.datapipes as dp\n",
    "except Exception:\n",
    "    dp = None\n",
    "\n",
    "if dp is None or 'torchdata.datapipes' not in sys.modules:\n",
    "    if 'torchdata' not in sys.modules:\n",
    "        td = types.ModuleType('torchdata')\n",
    "        sys.modules['torchdata'] = td\n",
    "    else:\n",
    "        td = sys.modules['torchdata']\n",
    "    dp = types.ModuleType('torchdata.datapipes')\n",
    "    td.datapipes = dp\n",
    "    sys.modules['torchdata.datapipes'] = dp\n",
    "\n",
    "if not hasattr(dp, 'iter'):\n",
    "    iter_mod = types.ModuleType('torchdata.datapipes.iter')\n",
    "    dp.iter = iter_mod\n",
    "    sys.modules['torchdata.datapipes.iter'] = iter_mod\n",
    "if not hasattr(dp.iter, 'IterDataPipe'):\n",
    "    class IterDataPipe(torch.utils.data.IterableDataset):\n",
    "        def __iter__(self): return iter([])\n",
    "    dp.iter.IterDataPipe = IterDataPipe\n",
    "\n",
    "if not hasattr(dp, 'map'):\n",
    "    map_mod = types.ModuleType('torchdata.datapipes.map')\n",
    "    dp.map = map_mod\n",
    "    sys.modules['torchdata.datapipes.map'] = map_mod\n",
    "if not hasattr(dp.map, 'MapDataPipe'):\n",
    "    class MapDataPipe(torch.utils.data.Dataset):\n",
    "        def __getitem__(self, idx): return None\n",
    "    dp.map.MapDataPipe = MapDataPipe\n",
    "\n",
    "def functional_datapipe(name, enable_df_api=False):\n",
    "    def decorator(cls):\n",
    "        def method(*args, **kwargs):\n",
    "            return cls(*args, **kwargs)\n",
    "        if hasattr(dp, 'iter') and hasattr(dp.iter, 'IterDataPipe'):\n",
    "            setattr(dp.iter.IterDataPipe, name, method)\n",
    "        if hasattr(dp, 'map') and hasattr(dp.map, 'MapDataPipe'):\n",
    "            setattr(dp.map.MapDataPipe, name, method)\n",
    "        try:\n",
    "            if hasattr(torch.utils.data, 'IterDataPipe'):\n",
    "                setattr(torch.utils.data.IterDataPipe, name, method)\n",
    "            if hasattr(torch.utils.data, 'MapDataPipe'):\n",
    "                setattr(torch.utils.data.MapDataPipe, name, method)\n",
    "        except Exception:\n",
    "            pass\n",
    "        return cls\n",
    "    return decorator\n",
    "\n",
    "dp.functional_datapipe = functional_datapipe\n",
    "print(\"✅ Môi trường STAIR-Enhanced & Dependencies đã sẵn sàng cho Clothing 512D!\")\n"
]

# Cell 2: Clothing Data Scanner & Adapter
cell2_source = [
    "# Cell 2: Tự Động Quét & Chuẩn Hóa Dữ Liệu Clothing Sang Chuẩn FreeRec/STAIR\n",
    "import os, pickle, shutil, time, zipfile\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import torch\n",
    "\n",
    "DATA_ROOT = '/kaggle/data'\n",
    "PROCESSED_ROOT = os.path.join(DATA_ROOT, 'Processed')\n",
    "LOCAL_DATA = os.path.join(os.getcwd(), 'data')\n",
    "LOCAL_PROCESSED = os.path.join(LOCAL_DATA, 'Processed')\n",
    "\n",
    "CANONICAL_NAMES = ['Amazon2014Clothing_550_MMRec', 'clothing']\n",
    "REQUIRED_PROCESSED_FILES = [\n",
    "    'train.txt', 'valid.txt', 'test.txt',\n",
    "    'visual_modality.pkl', 'textual_modality.pkl'\n",
    "]\n",
    "\n",
    "def bridge_directories(src_path):\n",
    "    for folder in CANONICAL_NAMES:\n",
    "        for base_dir in [PROCESSED_ROOT, DATA_ROOT, LOCAL_DATA, LOCAL_PROCESSED]:\n",
    "            dst = os.path.join(base_dir, folder)\n",
    "            if os.path.abspath(src_path) != os.path.abspath(dst):\n",
    "                os.makedirs(os.path.dirname(dst), exist_ok=True)\n",
    "                if os.path.islink(dst) or os.path.exists(dst):\n",
    "                    try:\n",
    "                        if os.path.islink(dst):\n",
    "                            os.unlink(dst)\n",
    "                        else:\n",
    "                            shutil.rmtree(dst, ignore_errors=True)\n",
    "                    except Exception:\n",
    "                        pass\n",
    "                try:\n",
    "                    os.symlink(src_path, dst)\n",
    "                except Exception:\n",
    "                    shutil.copytree(src_path, dst, dirs_exist_ok=True)\n",
    "\n",
    "def convert_raw_clothing(inter_path, text_npy_path, img_npy_path, dst_dir):\n",
    "    print(f\"🔄 Đang chuyển đổi dữ liệu Clothing từ {inter_path} sang chuẩn FreeRec ({dst_dir})...\")\n",
    "    os.makedirs(dst_dir, exist_ok=True)\n",
    "\n",
    "    df = pd.read_csv(inter_path, sep='\\t')\n",
    "    print(f\"  • Tổng số tương tác: {len(df):,}\")\n",
    "    print(f\"  • Số người dùng (Users): {df['userID'].nunique():,} | Số mặt hàng (Items): {df['itemID'].nunique():,}\")\n",
    "\n",
    "    splits = [\n",
    "        ('train.txt', df[df['x_label'] == 0]),\n",
    "        ('valid.txt', df[df['x_label'] == 1]),\n",
    "        ('test.txt',  df[df['x_label'] == 2]),\n",
    "    ]\n",
    "    for fname, sub_df in splits:\n",
    "        out_p = os.path.join(dst_dir, fname)\n",
    "        with open(out_p, 'w', encoding='utf-8') as f:\n",
    "            f.write(\"USER\\tITEM\\tTIMESTAMP\\n\")\n",
    "            for u, i, t in zip(sub_df['userID'], sub_df['itemID'], sub_df['timestamp']):\n",
    "                f.write(f\"{u}\\t{i}\\t{t}\\n\")\n",
    "        print(f\"  [Đã sinh] {fname}: {len(sub_df):,} tương tác -> {out_p}\")\n",
    "\n",
    "    if os.path.exists(text_npy_path):\n",
    "        text_feat = np.load(text_npy_path)\n",
    "        text_tensor = torch.from_numpy(text_feat.astype(np.float32))\n",
    "        with open(os.path.join(dst_dir, 'textual_modality.pkl'), 'wb') as f:\n",
    "            pickle.dump(text_tensor, f, protocol=pickle.HIGHEST_PROTOCOL)\n",
    "        print(f\"  [Đã sinh] textual_modality.pkl: {text_tensor.shape} ({text_tensor.dtype})\")\n",
    "\n",
    "    if os.path.exists(img_npy_path):\n",
    "        img_feat = np.load(img_npy_path)\n",
    "        img_tensor = torch.from_numpy(img_feat.astype(np.float32))\n",
    "        with open(os.path.join(dst_dir, 'visual_modality.pkl'), 'wb') as f:\n",
    "            pickle.dump(img_tensor, f, protocol=pickle.HIGHEST_PROTOCOL)\n",
    "        print(f\"  [Đã sinh] visual_modality.pkl: {img_tensor.shape} ({img_tensor.dtype})\")\n",
    "\n",
    "    print(\"✅ Hoàn tất chuyển đổi Clothing sang chuẩn FreeRec/STAIR!\")\n",
    "\n",
    "def scan_and_prepare_clothing():\n",
    "    target_processed = os.path.join(PROCESSED_ROOT, 'Amazon2014Clothing_550_MMRec')\n",
    "\n",
    "    for folder in CANONICAL_NAMES:\n",
    "        for cand in [os.path.join(PROCESSED_ROOT, folder), os.path.join(DATA_ROOT, folder), os.path.join(LOCAL_PROCESSED, folder)]:\n",
    "            if os.path.exists(cand) and all(os.path.exists(os.path.join(cand, f)) for f in REQUIRED_PROCESSED_FILES):\n",
    "                print(f\"✅ Dữ liệu Clothing đã tồn tại sẵn tại: {cand}\")\n",
    "                bridge_directories(cand)\n",
    "                return cand\n",
    "\n",
    "    print(\"🔍 Đang quét /kaggle/input để tìm kiếm tập dữ liệu Clothing...\")\n",
    "    input_base = '/kaggle/input'\n",
    "    raw_inter = None\n",
    "    raw_text = None\n",
    "    raw_img = None\n",
    "\n",
    "    for attempt in range(12):\n",
    "        if os.path.exists(input_base):\n",
    "            for root, dirs, files in os.walk(input_base):\n",
    "                if all(rf in files for rf in REQUIRED_PROCESSED_FILES):\n",
    "                    print(f\"  [TÌM THẤY DỮ LIỆU ĐÃ XỬ LÝ] {root}\")\n",
    "                    os.makedirs(target_processed, exist_ok=True)\n",
    "                    for f in files:\n",
    "                        shutil.copy2(os.path.join(root, f), os.path.join(target_processed, f))\n",
    "                    bridge_directories(target_processed)\n",
    "                    return target_processed\n",
    "\n",
    "                if 'clothing.inter' in files:\n",
    "                    raw_inter = os.path.join(root, 'clothing.inter')\n",
    "                    raw_text = os.path.join(root, 'text_feat.npy')\n",
    "                    raw_img = os.path.join(root, 'image_feat.npy')\n",
    "                    break\n",
    "            if raw_inter:\n",
    "                break\n",
    "\n",
    "        for zname in ['clothing.zip', 'Amazon2014Clothing_550_MMRec.zip']:\n",
    "            repo_zip = os.path.join(LOCAL_DATA, zname)\n",
    "            if not raw_inter and os.path.exists(repo_zip):\n",
    "                print(f\"📦 Phát hiện tệp nén {repo_zip}. Đang giải nén...\")\n",
    "                ext_dir = os.path.join(LOCAL_DATA, 'raw_clothing')\n",
    "                with zipfile.ZipFile(repo_zip, 'r') as zf:\n",
    "                    zf.extractall(ext_dir)\n",
    "                for root, dirs, files in os.walk(ext_dir):\n",
    "                    if 'clothing.inter' in files:\n",
    "                        raw_inter = os.path.join(root, 'clothing.inter')\n",
    "                        raw_text = os.path.join(root, 'text_feat.npy')\n",
    "                        raw_img = os.path.join(root, 'image_feat.npy')\n",
    "                        break\n",
    "                    if all(rf in files for rf in REQUIRED_PROCESSED_FILES):\n",
    "                        bridge_directories(root)\n",
    "                        return root\n",
    "\n",
    "        if raw_inter:\n",
    "            break\n",
    "        print(f\"⏳ Dataset đang được tải về từ Kaggle... Đợi 5s (lần {attempt+1}/12)...\")\n",
    "        time.sleep(5)\n",
    "\n",
    "    if raw_inter and os.path.exists(raw_inter):\n",
    "        convert_raw_clothing(raw_inter, raw_text, raw_img, target_processed)\n",
    "        bridge_directories(target_processed)\n",
    "        return target_processed\n",
    "    else:\n",
    "        print(\"❌ Không tìm thấy tập dữ liệu Clothing trong /kaggle/input hoặc trong repository!\")\n",
    "        return None\n",
    "\n",
    "prepared_clothing_dir = scan_and_prepare_clothing()\n",
    "print(\"=\" * 75)\n",
    "p_dir = os.path.join(PROCESSED_ROOT, 'Amazon2014Clothing_550_MMRec')\n",
    "ready_files = [f for f in REQUIRED_PROCESSED_FILES if os.path.exists(os.path.join(p_dir, f))]\n",
    "status = f\"✅ {len(ready_files)}/{len(REQUIRED_PROCESSED_FILES)} tệp chuẩn sẵn sàng\" if len(ready_files) == len(REQUIRED_PROCESSED_FILES) else \"❌ THIẾU\"\n",
    "print(f\"TỔNG KẾT DỮ LIỆU CLOTHING: {status} trong {p_dir}\")\n",
    "for rf in REQUIRED_PROCESSED_FILES:\n",
    "    fp = os.path.join(p_dir, rf)\n",
    "    if os.path.exists(fp):\n",
    "        sz = os.path.getsize(fp) / (1024 * 1024)\n",
    "        print(f\"  • {rf:25s}: {sz:.2f} MB\")\n",
    "print(\"=\" * 75)\n"
]

# Cell 3: Runner Engine
cell3_source = [
    "# Cell 3: Runner Engine Huấn Luyện STAIR Baseline (512D)\n",
    "import subprocess, sys, os, time, re, threading\n",
    "\n",
    "try:\n",
    "    import pynvml\n",
    "    pynvml.nvmlInit()\n",
    "    HAS_NVML = True\n",
    "except Exception:\n",
    "    HAS_NVML = False\n",
    "\n",
    "def get_gpu_memory_used():\n",
    "    if not HAS_NVML:\n",
    "        return 0.0\n",
    "    try:\n",
    "        handle = pynvml.nvmlDeviceGetHandleByIndex(0)\n",
    "        info = pynvml.nvmlDeviceGetMemoryInfo(handle)\n",
    "        return info.used / (1024 ** 2)\n",
    "    except Exception:\n",
    "        return 0.0\n",
    "\n",
    "TRACKED_METRICS = ['Recall@10', 'Recall@20', 'NDCG@10', 'NDCG@20']\n",
    "\n",
    "def extract_best_test(log_path):\n",
    "    if not os.path.exists(log_path):\n",
    "        return None, {}\n",
    "\n",
    "    with open(log_path, 'r', encoding='utf-8', errors='ignore') as f:\n",
    "        content = f.read()\n",
    "        lines = content.splitlines()\n",
    "\n",
    "    best_epoch = None\n",
    "    best_metrics = {}\n",
    "\n",
    "    # 1. Tìm best_epoch từ log FreeRec\n",
    "    m_load = re.findall(r'Load best model @Epoch\\s+(\\d+)', content)\n",
    "    if m_load:\n",
    "        best_epoch = int(m_load[-1])\n",
    "    else:\n",
    "        m_tbl = re.findall(r'valid\\s+NDCG@20\\s+[0-9.]+\\s+(\\d+)', content)\n",
    "        if m_tbl:\n",
    "            best_epoch = int(m_tbl[-1])\n",
    "        else:\n",
    "            m_new = re.findall(r'NEW BEST MODEL @Epoch\\s+(\\d+)', content)\n",
    "            if m_new:\n",
    "                best_epoch = int(m_new[-1])\n",
    "\n",
    "    # 2. Tìm metrics TEST tại best_epoch hoặc dòng TEST summary cuối cùng\n",
    "    test_lines = [l for l in lines if 'TEST @Epoch:' in l and '||' in l]\n",
    "    target_line = None\n",
    "    if best_epoch is not None:\n",
    "        for tl in reversed(test_lines):\n",
    "            if f\"TEST @Epoch: {best_epoch}\" in tl or f\"TEST @Epoch:{best_epoch}\" in tl:\n",
    "                target_line = tl\n",
    "                break\n",
    "\n",
    "    if not target_line and test_lines:\n",
    "        target_line = test_lines[-1]\n",
    "        if best_epoch is None:\n",
    "            m_ep = re.search(r'TEST @Epoch:\\s*(\\d+)', target_line)\n",
    "            if m_ep:\n",
    "                best_epoch = int(m_ep.group(1))\n",
    "\n",
    "    if target_line:\n",
    "        for metric in TRACKED_METRICS:\n",
    "            m = re.search(rf'{re.escape(metric)}\\s+(?:Avg:\\s*|:\\s*)([0-9.]+)', target_line, re.IGNORECASE)\n",
    "            if m:\n",
    "                best_metrics[metric] = float(m.group(1))\n",
    "\n",
    "    # 3. Fallback quét bảng Mode Metric Best @Epoch\n",
    "    if len(best_metrics) < 4:\n",
    "        for line in lines:\n",
    "            for metric in TRACKED_METRICS:\n",
    "                if metric not in best_metrics:\n",
    "                    m = re.search(rf'test\\s+{re.escape(metric)}\\s+([0-9.]+)', line, re.IGNORECASE)\n",
    "                    if m:\n",
    "                        best_metrics[metric] = float(m.group(1))\n",
    "\n",
    "    return best_epoch, best_metrics\n",
    "\n",
    "def run_stair_baseline(\n",
    "    key, yaml_cfg, data_root, log_path,\n",
    "    epochs=500,\n",
    "    embedding_dim=512,\n",
    "    batch_size=2048,\n",
    "    patience=30,\n",
    "    mfiles='textual_modality.pkl,visual_modality.pkl',\n",
    "    num_neighbors='5-1',\n",
    "    **kwargs\n",
    "):\n",
    "    print('=' * 85)\n",
    "    print(f'🚀 BẮT ĐẦU HUẤN LUYỆN: {key.upper()} | METHOD: [STAIR_BASELINE] | DIM: [{embedding_dim}] | EPOCHS: [{epochs}]')\n",
    "    print(f'  * Dataset Key         : {key}')\n",
    "    print(f'  * Method              : STAIR Baseline')\n",
    "    print(f'  * Embedding Dim       : {embedding_dim} (Không gian mở rộng 512D)')\n",
    "    print(f'  * Modal kNN Neighbors : {num_neighbors} (Text: 5, Vision: 1)')\n",
    "    print(f'  * Batch Size          : {batch_size}')\n",
    "    print(f'  * Max Epochs          : {epochs}')\n",
    "    print(f'  * Early Stop Patience : {patience} eps')\n",
    "    print(f'  * Target Metric       : NDCG@20 (N@20)')\n",
    "    print(f'  * Log Path            : {log_path}')\n",
    "    print('=' * 85)\n",
    "\n",
    "    os.makedirs(os.path.dirname(log_path), exist_ok=True)\n",
    "    t0 = time.time()\n",
    "    runner_py = '/kaggle/working/STAIR-Enhanced/main.py'\n",
    "    if not os.path.exists(runner_py):\n",
    "        runner_py = 'main.py'\n",
    "\n",
    "    cmd = [\n",
    "        sys.executable, runner_py,\n",
    "        '--config',           yaml_cfg,\n",
    "        '--root',             data_root,\n",
    "        '--epochs',           str(epochs),\n",
    "        '--embedding-dim',    str(embedding_dim),\n",
    "        '--batch-size',       str(batch_size),\n",
    "        '--patience',         str(patience),\n",
    "        '--mfiles',           mfiles,\n",
    "        '--num-neighbors',    num_neighbors,\n",
    "    ]\n",
    "\n",
    "    with open(log_path, 'w', encoding='utf-8') as f:\n",
    "        proc = subprocess.Popen(\n",
    "            cmd,\n",
    "            stdout=subprocess.PIPE,\n",
    "            stderr=subprocess.STDOUT,\n",
    "            text=True,\n",
    "            bufsize=1\n",
    "        )\n",
    "        for line in proc.stdout:\n",
    "            print(line, end='', flush=True)\n",
    "            f.write(line)\n",
    "            f.flush()\n",
    "        proc.wait()\n",
    "\n",
    "    elapsed = time.time() - t0\n",
    "    print('=' * 85)\n",
    "    if proc.returncode != 0:\n",
    "        print(f'⚠️ [CẢNH BÁO] STAIR Baseline kết thúc với mã {proc.returncode}.')\n",
    "    else:\n",
    "        print(f'✅ [HOÀN TẤT] STAIR Baseline (512D) thành công trong {elapsed/60:.2f} phút ({elapsed:.1f}s)!')\n",
    "\n",
    "    best_ep, metrics = extract_best_test(log_path)\n",
    "    print(f'  * Checkpoint tối ưu : Epoch {best_ep}')\n",
    "    for m, val in metrics.items():\n",
    "        print(f'  * {m:12s}: {val:.4f}')\n",
    "    print('=' * 85)\n",
    "    return best_ep, metrics\n"
]

# Cell 4: Markdown Section - Train Baseline 512D
cell4_source = [
    "## 🏋️ Huấn luyện STAIR Baseline trên Clothing ở không gian 512D\n",
    "Khởi chạy huấn luyện **STAIR Baseline** với `embedding_dim: 512`:\n",
    "- Toàn bộ biểu diễn User, Item và đặc trưng nén SVD (Text 384D $\\to$ 512D, Image 4096D $\\to$ 512D) đều được đồng bộ lên **512 chiều**.\n",
    "- Giữ nguyên cơ chế tích chập chuyển tiếp FSC/BSC và ma trận mAdj kNN truyền thống của tác giả."
]

# Cell 5: Code Section - Execute Baseline 512D
cell5_source = [
    "# Cell 5: Huấn luyện STAIR Baseline (512D, kNN 5-1, Batch 2048)\n",
    "DATA_ROOT = '/kaggle/data'\n",
    "YAML_PATH = '/kaggle/working/STAIR-Enhanced/configs/Amazon2014Clothing_550_MMRec.yaml'\n",
    "LOG_BASELINE_512D = '/kaggle/working/logs/baseline/clothing_stair_baseline_dim512.log'\n",
    "\n",
    "run_stair_baseline(\n",
    "    key='Amazon2014Clothing_550_MMRec',\n",
    "    yaml_cfg=YAML_PATH,\n",
    "    data_root=DATA_ROOT,\n",
    "    log_path=LOG_BASELINE_512D,\n",
    "    epochs=500,\n",
    "    embedding_dim=512,\n",
    "    batch_size=2048,\n",
    "    patience=30,\n",
    "    mfiles='textual_modality.pkl,visual_modality.pkl',\n",
    "    num_neighbors='5-1',\n",
    ")\n"
]

# Cell 6: Markdown Section - Comparison Table
cell6_source = [
    "## 📊 Bảng Đối Sánh Khoa Học Đa Chiều: Baseline 64D vs Baseline 512D vs DCD-Gated 512D\n",
    "Bảng tổng hợp kết quả đối sánh 3 cấu hình thực nghiệm trên **Amazon Clothing (Sparsity 99.97%)**:\n",
    "1. **STAIR Baseline (64D):** Cấu hình chuẩn của tác giả trong bài báo gốc.\n",
    "2. **STAIR Baseline (512D):** Cấu hình mở rộng số chiều tự thân của Baseline vừa chạy.\n",
    "3. **STAIR DCD-Gated (512D):** Phương pháp cải tiến đột phá (Đồng thuận kép Ochiai $\\odot$ Multimodal + Van Gating Residuals)."
]

# Cell 7: Code Section - Summary Table
cell7_source = [
    "# Cell 7: Bảng Tổng Kết Đối Sánh Đa Chiều (PrettyTable)\n",
    "import os\n",
    "from prettytable import PrettyTable\n",
    "\n",
    "# Mốc thực nghiệm STAIR Baseline (64D) đã xác lập trên Clothing\n",
    "BASELINE_64D = {\n",
    "    'epoch': 205,\n",
    "    'Recall@10': 0.0596,\n",
    "    'Recall@20': 0.0896,\n",
    "    'NDCG@10':   0.0321,\n",
    "    'NDCG@20':   0.0398,\n",
    "}\n",
    "\n",
    "# Mốc thực nghiệm STAIR DCD-Gated (512D) đã xác lập trên Clothing\n",
    "DCD_GATED_512D = {\n",
    "    'epoch': 30,\n",
    "    'Recall@10': 0.0644,\n",
    "    'Recall@20': 0.0940,\n",
    "    'NDCG@10':   0.0354,\n",
    "    'NDCG@20':   0.0431,\n",
    "}\n",
    "\n",
    "table = PrettyTable()\n",
    "table.field_names = ['Tập dữ liệu', 'Phương pháp', 'Số chiều', 'Recall@10', 'Recall@20', 'NDCG@10', 'NDCG@20', 'Δ vs Base 64D', 'Δ vs Base 512D']\n",
    "\n",
    "# 1. Dòng Baseline 64D\n",
    "table.add_row([\n",
    "    'CLOTHING', f\"STAIR Baseline [@Ep{BASELINE_64D['epoch']}]\", '64D',\n",
    "    f\"{BASELINE_64D['Recall@10']:.4f}\", f\"{BASELINE_64D['Recall@20']:.4f}\",\n",
    "    f\"{BASELINE_64D['NDCG@10']:.4f}\", f\"{BASELINE_64D['NDCG@20']:.4f}\",\n",
    "    '-', '-'\n",
    "])\n",
    "\n",
    "# 2. Dòng Baseline 512D vừa chạy\n",
    "log_512d = '/kaggle/working/logs/baseline/clothing_stair_baseline_dim512.log'\n",
    "ep_512, m_512 = extract_best_test(log_512d)\n",
    "base_512_n20 = None\n",
    "\n",
    "if m_512 and len(m_512) >= 4:\n",
    "    base_512_n20 = m_512['NDCG@20']\n",
    "    gain_vs_64 = (m_512['NDCG@20'] - BASELINE_64D['NDCG@20']) / BASELINE_64D['NDCG@20'] * 100\n",
    "    sign_64 = '+' if gain_vs_64 >= 0 else ''\n",
    "    table.add_row([\n",
    "        'CLOTHING', f\"STAIR Baseline [@Ep{ep_512}]\", '512D',\n",
    "        f\"{m_512['Recall@10']:.4f}\", f\"{m_512['Recall@20']:.4f}\",\n",
    "        f\"{m_512['NDCG@10']:.4f}\", f\"{m_512['NDCG@20']:.4f}\",\n",
    "        f\"{sign_64}{gain_vs_64:.2f}%\", '-'\n",
    "    ])\n",
    "else:\n",
    "    table.add_row([\n",
    "        'CLOTHING', 'STAIR Baseline (Đang chạy...)', '512D',\n",
    "        '-', '-', '-', '-', '-', '-'\n",
    "    ])\n",
    "\n",
    "# 3. Dòng DCD-Gated 512D\n",
    "gain_dcd_vs_64 = (DCD_GATED_512D['NDCG@20'] - BASELINE_64D['NDCG@20']) / BASELINE_64D['NDCG@20'] * 100\n",
    "sign_dcd_64 = '+' if gain_dcd_vs_64 >= 0 else ''\n",
    "\n",
    "delta_vs_512_str = '-'\n",
    "if base_512_n20 is not None:\n",
    "    gain_dcd_vs_512 = (DCD_GATED_512D['NDCG@20'] - base_512_n20) / base_512_n20 * 100\n",
    "    sign_512 = '+' if gain_dcd_vs_512 >= 0 else ''\n",
    "    delta_vs_512_str = f\"{sign_512}{gain_dcd_vs_512:.2f}%\"\n",
    "\n",
    "table.add_row([\n",
    "    'CLOTHING', f\"★ STAIR DCD-Gated [@Ep{DCD_GATED_512D['epoch']}]\", '512D',\n",
    "    f\"{DCD_GATED_512D['Recall@10']:.4f}\", f\"{DCD_GATED_512D['Recall@20']:.4f}\",\n",
    "    f\"{DCD_GATED_512D['NDCG@10']:.4f}\", f\"{DCD_GATED_512D['NDCG@20']:.4f}\",\n",
    "    f\"{sign_dcd_64}{gain_dcd_vs_64:.2f}%\", delta_vs_512_str\n",
    "])\n",
    "\n",
    "print(table)\n",
    "\n",
    "print('\\n' + '=' * 85)\n",
    "print(\"🎉 KẾT LUẬN BÓC TÁCH HIỆU NĂNG (ABLATION STUDY) TRÊN CLOTHING:\")\n",
    "print(f\"  • Baseline 64D  : NDCG@20 = {BASELINE_64D['NDCG@20']:.4f} (Mốc chuẩn gốc)\")\n",
    "if base_512_n20 is not None:\n",
    "    print(f\"  • Baseline 512D : NDCG@20 = {base_512_n20:.4f} ({sign_64}{gain_vs_64:.2f}% vs Base 64D)\")\n",
    "    print(f\"  • DCD-Gated 512D: NDCG@20 = {DCD_GATED_512D['NDCG@20']:.4f} ({delta_vs_512_str} vs Base 512D, {sign_dcd_64}{gain_dcd_vs_64:.2f}% vs Base 64D)\")\n",
    "else:\n",
    "    print(f\"  • DCD-Gated 512D: NDCG@20 = {DCD_GATED_512D['NDCG@20']:.4f} ({sign_dcd_64}{gain_dcd_vs_64:.2f}% vs Base 64D)\")\n",
    "print('=' * 85)\n"
]

new_cells = [
    {"cell_type": "markdown", "metadata": {}, "source": cell0_source},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": cell1_source},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": cell2_source},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": cell3_source},
    {"cell_type": "markdown", "metadata": {}, "source": cell4_source},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": cell5_source},
    {"cell_type": "markdown", "metadata": {}, "source": cell6_source},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": cell7_source},
]

nb["cells"] = new_cells

out_path = r"d:\STAIR-Enhanced\notebook\stair_clothing_512d.ipynb"
os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"[OK] Successfully generated notebook for Clothing 512D: {out_path}")
