# -*- coding: utf-8 -*-
"""
scripts/generate_tiktok_notebook.py
====================================
Tạo notebook chuyên biệt cho TikTok (Tri-modal Micro-video): notebook/stair_tiktok.ipynb
- Phương pháp đột phá: DCD-Gated (Dual-Consensus Denoising & Gated Residuals).
- Cấu hình: Dim=256D, Batch Size=2048, Cosine LR Warmup 15 eps, Patience=30, Max Epochs=500.
- Tự động quét và phát hiện dataset TikTok từ /kaggle/input/tiktok/tiktok, /kaggle/input/Tiktok/tiktok,
  hoặc giải nén tự động từ data/tiktok.zip trong repository.
- Tự động chuyển đổi định dạng raw DiffMM (trnMat.pkl, audio_feat.npy, ...) sang chuẩn FreeRec/STAIR.
- Đối sánh kết quả trực tiếp với STAIR Baseline (64D) trên toàn bộ 4 chỉ số khoa học.
"""
import copy
import json
import os

with open(r"d:\STAIR-Enhanced\models\stair_breakthrough.py", "r", encoding="utf-8") as f:
    breakthrough_model_code = f.read()

with open(r"d:\STAIR-Enhanced\models\stair_ne_nlgcl_v5_plus.py", "r", encoding="utf-8") as f:
    v5_plus_model_code = f.read()

with open(r"d:\STAIR-Enhanced\main_stair_ne_nlgcl_v5_plus.py", "r", encoding="utf-8") as f:
    runner_code = f.read()

with open(r"d:\STAIR-Enhanced\configs\tiktok_MMRec.yaml", "r", encoding="utf-8") as f:
    tiktok_yaml_code = f.read()

template_path = r"d:\STAIR-Enhanced\notebook\stair_electronics.ipynb"
with open(template_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

# Clear outputs and execution count for clean notebook
for cell in nb["cells"]:
    if cell.get("cell_type") == "code":
        cell["outputs"] = []
        cell["execution_count"] = None

# Cell 0: Header
nb["cells"][0]["source"] = [
    "# 🚀 GIAI ĐOẠN 3: STAIR DCD-GATED TRÊN TIKTOK (TRI-MODAL MICRO-VIDEO)\n",
    "## 🏆 Tri-modal (Vision + Text + Audio) | Embedding Dim = 256 | Batch Size = 2048 | Cosine Warmup LR (15 eps) | Patience = 30 | Checkpoint: NDCG@20 (500 eps)\n",
    "*(Tập trung độc quyền trên tập dữ liệu video ngắn đa phương tiện: **TikTok (DiffMM / ACM MM 2024 Benchmark - 9,308 Users, 6,710 Items)**)*\n",
    "---\n",
    "### 🎯 PHƯƠNG PHÁP ĐỘT PHÁ TRIỂN KHAI:\n",
    "* **`dcd_gated` (Dual-Consensus Denoising & Gated Residuals):**\n",
    "  - Đã thiết lập kỷ lục nhảy vọt **+14.00% NDCG@20 (+18.27% NDCG@10)** trên Amazon Sports.\n",
    "  - **Đặc thù Tri-modal trên TikTok:** Video ngắn phối hợp đồng thời 3 phương thức: **Thị giác (Image - 128D)**, **Âm thanh (Audio - 128D)** và **Văn bản ngữ nghĩa (Text - 768D)**.\n",
    "  - Cơ chế làm dày cạnh ảo đồng thuận kép: Đồng thuận hành vi xem video (Ochiai) $\\odot$ Tương đồng đặc trưng đa phương thức (Tri-modal FSC).\n",
    "  - Van Gating an toàn tự động đóng lại khi tín hiệu nhiễu, chống suy thoái biểu diễn trong không gian đa giác quan.\n",
    "---\n",
    "### 📌 CẤU HÌNH THAM SỐ:\n",
    "* **Dataset:** `tiktok` (Batch size: 2048, Gamma: 0.05, Modal files: `visual_modality.pkl,textual_modality.pkl,audio_modality.pkl`, kNN: `3-3-3`).\n",
    "* **Embedding Dimension:** `256` (gấp 4 lần Baseline 64D).\n",
    "* **Max Epochs:** `500` epochs với **Early Stopping Patience = 30 epochs** theo chỉ số trọng tâm **`NDCG@20`**.\n",
    "* **Cosine LR Warmup:** 15 epoch đầu tăng tuyến tính từ `1e-6` -> `1e-3`, sau đó decay theo Cosine về `1e-6`.\n"
]

# Cell 1: Environment & Sync (embedded code)
cell1_source = [
    "# Cell 1: Môi trường, Dependencies & Đồng bộ STAIR-Enhanced\n",
    "import os, shutil, subprocess, sys\n",
    "\n",
    "STAIR_DIR = '/kaggle/working/STAIR-Enhanced'\n",
    "os.chdir('/kaggle/working')\n",
    "\n",
    "# 1. Luôn clone hoặc đồng bộ cưỡng bức repository mới nhất từ origin/main\n",
    "if os.path.exists(STAIR_DIR):\n",
    "    print(\"Thư mục STAIR-Enhanced đã tồn tại. Đang đồng bộ cưỡng bức mã nguồn mới nhất...\")\n",
    "    try:\n",
    "        subprocess.run(['git', '-C', STAIR_DIR, 'fetch', 'origin', 'main'], check=True)\n",
    "        subprocess.run(['git', '-C', STAIR_DIR, 'reset', '--hard', 'origin/main'], check=True)\n",
    "        print(\"✅ Đã reset về commit mới nhất của origin/main.\")\n",
    "    except Exception as e:\n",
    "        print(f\"Lỗi git fetch/reset ({e}), đang làm sạch và clone lại từ đầu...\")\n",
    "        shutil.rmtree(STAIR_DIR, ignore_errors=True)\n",
    "\n",
    "if not os.path.exists(STAIR_DIR):\n",
    "    print(\"Cloning STAIR-Enhanced repository (branch main)...\" )\n",
    "    subprocess.run([\n",
    "        'git', 'clone', '--depth', '1',\n",
    "        'https://github.com/HenryBui777/STAIR-Enhanced.git', STAIR_DIR\n",
    "    ], check=True)\n",
    "\n",
    "for p in [STAIR_DIR, '/kaggle/working']:\n",
    "    if p not in sys.path:\n",
    "        sys.path.insert(0, p)\n",
    "\n",
    "if os.path.exists(STAIR_DIR):\n",
    "    os.chdir(STAIR_DIR)\n",
    "\n",
    "# Ghi đảm bảo module breakthrough, v5_plus, runner và config tồn tại trên đĩa\n",
    "os.makedirs(os.path.join(STAIR_DIR, 'models'), exist_ok=True)\n",
    "os.makedirs(os.path.join(STAIR_DIR, 'configs'), exist_ok=True)\n",
    "with open(os.path.join(STAIR_DIR, 'models', 'stair_breakthrough.py'), 'w', encoding='utf-8') as f:\n",
    f"    f.write({repr(breakthrough_model_code)})\n",
    "with open(os.path.join(STAIR_DIR, 'models', 'stair_ne_nlgcl_v5_plus.py'), 'w', encoding='utf-8') as f:\n",
    f"    f.write({repr(v5_plus_model_code)})\n",
    "with open(os.path.join(STAIR_DIR, 'main_stair_ne_nlgcl_v5_plus.py'), 'w', encoding='utf-8') as f:\n",
    f"    f.write({repr(runner_code)})\n",
    "with open(os.path.join(STAIR_DIR, 'configs', 'tiktok_MMRec.yaml'), 'w', encoding='utf-8') as f:\n",
    f"    f.write({repr(tiktok_yaml_code)})\n",
    "\n",
    "# Xóa cache module để kernel luôn nạp phiên bản mới nhất từ đĩa\n",
    "for mod_name in list(sys.modules.keys()):\n",
    "    if 'stair_ne_nlgcl' in mod_name or 'stair_breakthrough' in mod_name:\n",
    "        sys.modules.pop(mod_name, None)\n",
    "\n",
    "# 2. Cài đặt các gói phụ thuộc bắt buộc\n",
    "print(\"📦 Cài đặt dependencies (torchdata, torch_geometric, freerec, nvidia-ml-py, prettytable, scipy)...\")\n",
    "subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '--no-deps', 'torchdata==0.7.1'], check=False)\n",
    "subprocess.run([\n",
    "    sys.executable, '-m', 'pip', 'install', '-q',\n",
    "    'torch_geometric', 'freerec==0.8.5', 'nvidia-ml-py', 'prettytable', 'matplotlib', 'pyyaml', 'seaborn', 'scipy'\n",
    "], check=True)\n",
    "\n",
    "# 3. Kaggle TorchData compatibility shims cho FreeRec (PyTorch 2.x & Python 3.10+)\n",
    "import types\n",
    "import torch.utils.data\n",
    "\n",
    "try:\n",
    "    import torchdata\n",
    "    import torchdata.datapipes as dp\n",
    "except Exception:\n",
    "    dp = None\n",
    "\n",
    "if dp is None or 'torchdata.datapipes' not in sys.modules:\n",
    "    if 'torchdata' not in sys.modules:\n",
    "        td = types.ModuleType('torchdata')\n",
    "        sys.modules['torchdata'] = td\n",
    "    else:\n",
    "        td = sys.modules['torchdata']\n",
    "    dp = types.ModuleType('torchdata.datapipes')\n",
    "    td.datapipes = dp\n",
    "    sys.modules['torchdata.datapipes'] = dp\n",
    "\n",
    "if not hasattr(dp, 'iter'):\n",
    "    iter_mod = types.ModuleType('torchdata.datapipes.iter')\n",
    "    dp.iter = iter_mod\n",
    "    sys.modules['torchdata.datapipes.iter'] = iter_mod\n",
    "if not hasattr(dp.iter, 'IterDataPipe'):\n",
    "    class IterDataPipe(torch.utils.data.IterableDataset):\n",
    "        def __iter__(self): return iter([])\n",
    "    dp.iter.IterDataPipe = IterDataPipe\n",
    "\n",
    "if not hasattr(dp, 'map'):\n",
    "    map_mod = types.ModuleType('torchdata.datapipes.map')\n",
    "    dp.map = map_mod\n",
    "    sys.modules['torchdata.datapipes.map'] = map_mod\n",
    "if not hasattr(dp.map, 'MapDataPipe'):\n",
    "    class MapDataPipe(torch.utils.data.Dataset):\n",
    "        def __getitem__(self, idx): raise NotImplementedError\n",
    "        def __len__(self): return 0\n",
    "    dp.map.MapDataPipe = MapDataPipe\n",
    "\n",
    "if not hasattr(dp, 'functional_datapipe'):\n",
    "    def functional_datapipe(name, enable_df_datapipes_support=False):\n",
    "        def decorator(cls):\n",
    "            def method(self, *args, **kwargs): return cls(self, *args, **kwargs)\n",
    "            if hasattr(dp, 'iter') and hasattr(dp.iter, 'IterDataPipe'): setattr(dp.iter.IterDataPipe, name, method)\n",
    "            if hasattr(dp, 'map') and hasattr(dp.map, 'MapDataPipe'): setattr(dp.map.MapDataPipe, name, method)\n",
    "            return cls\n",
    "        return decorator\n",
    "    dp.functional_datapipe = functional_datapipe\n",
    "\n",
    "print(\"✅ Môi trường STAIR-Enhanced & Dependencies đã hoàn tất sẵn sàng!\")\n"
]
nb["cells"][2]["source"] = cell1_source

# Cell 3: Intro to Data Preparation
nb["cells"][3]["source"] = [
    "## Cell 2 📂 Chuẩn bị & Chuyển đổi Dữ liệu TikTok từ Kaggle Input (Tự động Adapter sang FreeRec)\n",
    "Tự động quét toàn bộ `/kaggle/input` để phát hiện thư mục dữ liệu TikTok (chứa `trnMat.pkl`, `audio_feat.npy`, `image_feat.npy`, `text_feat.npy`, ...).\n",
    "- Nếu phát hiện dữ liệu thô (raw format từ DiffMM / ACM MM 2024), hệ thống tự động chuyển đổi sang chuẩn FreeRec (`train.txt`, `valid.txt`, `test.txt`, `visual_modality.pkl`, `textual_modality.pkl`, `audio_modality.pkl`).\n",
    "- Đồng thời liên kết (bridge/symlink) dữ liệu vào `/kaggle/data/Processed/tiktok` và `/kaggle/data/tiktok` sẵn sàng cho huấn luyện."
]

# Cell 4: Data Preparation & Conversion Code for TikTok
cell2_source = [
    "# Cell 2: Chuẩn bị và Chuyển đổi Dữ liệu TikTok (Tự động quét & Adapter sang FreeRec)\n",
    "import os, shutil, glob, time, pickle, zipfile\n",
    "import numpy as np\n",
    "import torch\n",
    "import scipy.sparse as sp\n",
    "\n",
    "DATA_ROOT = '/kaggle/data'\n",
    "PROCESSED_ROOT = os.path.join(DATA_ROOT, 'Processed')\n",
    "LOCAL_DATA = '/kaggle/working/STAIR-Enhanced/data'\n",
    "LOCAL_PROCESSED = os.path.join(LOCAL_DATA, 'Processed')\n",
    "\n",
    "for d in [DATA_ROOT, PROCESSED_ROOT, LOCAL_DATA, LOCAL_PROCESSED]:\n",
    "    os.makedirs(d, exist_ok=True)\n",
    "\n",
    "TARGET_FOLDER = 'tiktok'\n",
    "REQUIRED_PROCESSED_FILES = [\n",
    "    'train.txt', 'valid.txt', 'test.txt',\n",
    "    'visual_modality.pkl', 'textual_modality.pkl', 'audio_modality.pkl'\n",
    "]\n",
    "RAW_FILES = [\n",
    "    'trnMat.pkl', 'valMat.pkl', 'tstMat.pkl',\n",
    "    'audio_feat.npy', 'image_feat.npy', 'text_feat.npy'\n",
    "]\n",
    "\n",
    "def bridge_directories(src_dir, target_folder):\n",
    "    destinations = [\n",
    "        os.path.join(DATA_ROOT, target_folder),\n",
    "        os.path.join(PROCESSED_ROOT, target_folder),\n",
    "        os.path.join(LOCAL_DATA, target_folder),\n",
    "        os.path.join(LOCAL_PROCESSED, target_folder),\n",
    "    ]\n",
    "    for dst in destinations:\n",
    "        if os.path.abspath(src_dir) == os.path.abspath(dst):\n",
    "            continue\n",
    "        os.makedirs(dst, exist_ok=True)\n",
    "        for item in os.listdir(src_dir):\n",
    "            s_item = os.path.join(src_dir, item)\n",
    "            d_item = os.path.join(dst, item)\n",
    "            if os.path.isfile(s_item) and not os.path.exists(d_item):\n",
    "                try:\n",
    "                    os.symlink(s_item, d_item)\n",
    "                except Exception:\n",
    "                    shutil.copy2(s_item, d_item)\n",
    "\n",
    "def convert_raw_tiktok(src_dir, dst_dir):\n",
    "    print(f\"🔄 Đang thực hiện chuyển đổi TikTok dataset từ {src_dir} sang chuẩn FreeRec/STAIR ({dst_dir})...\")\n",
    "    os.makedirs(dst_dir, exist_ok=True)\n",
    "    \n",
    "    # 1. Copy raw files\n",
    "    for rf in RAW_FILES:\n",
    "        src_path = os.path.join(src_dir, rf)\n",
    "        dst_path = os.path.join(dst_dir, rf)\n",
    "        if os.path.exists(src_path) and not os.path.exists(dst_path):\n",
    "            shutil.copy2(src_path, dst_path)\n",
    "\n",
    "    # 2. Load interaction matrices\n",
    "    trn_mat = pickle.load(open(os.path.join(src_dir, \"trnMat.pkl\"), \"rb\"))\n",
    "    val_mat = pickle.load(open(os.path.join(src_dir, \"valMat.pkl\"), \"rb\"))\n",
    "    tst_mat = pickle.load(open(os.path.join(src_dir, \"tstMat.pkl\"), \"rb\"))\n",
    "\n",
    "    num_users, num_items = trn_mat.shape\n",
    "    print(f\"  • Kích thước Ma trận tương tác: {num_users} Users x {num_items} Items\")\n",
    "    print(f\"  • Train NNZ: {trn_mat.nnz:,} | Valid NNZ: {val_mat.nnz:,} | Test NNZ: {tst_mat.nnz:,}\")\n",
    "\n",
    "    # 3. Export interaction txt files (USER \\t ITEM \\t TIMESTAMP)\n",
    "    splits = [\n",
    "        (\"train.txt\", trn_mat),\n",
    "        (\"valid.txt\", val_mat),\n",
    "        (\"test.txt\", tst_mat)\n",
    "    ]\n",
    "\n",
    "    for fname, mat in splits:\n",
    "        out_path = os.path.join(dst_dir, fname)\n",
    "        if not hasattr(mat, 'row'):\n",
    "            mat = mat.tocoo()\n",
    "        rows = mat.row\n",
    "        cols = mat.col\n",
    "        order = np.lexsort((cols, rows))\n",
    "        sorted_rows = rows[order]\n",
    "        sorted_cols = cols[order]\n",
    "\n",
    "        with open(out_path, \"w\", encoding=\"utf-8\") as f:\n",
    "            f.write(\"USER\\tITEM\\tTIMESTAMP\\n\")\n",
    "            for u, i in zip(sorted_rows, sorted_cols):\n",
    "                f.write(f\"{u}\\t{i}\\t0\\n\")\n",
    "        print(f\"  [Đã sinh] {fname}: {len(sorted_rows):,} tương tác -> {out_path}\")\n",
    "\n",
    "    # 4. Load and process multimodal feature vectors\n",
    "    audio_feat = np.load(os.path.join(src_dir, \"audio_feat.npy\"))\n",
    "    image_feat = np.load(os.path.join(src_dir, \"image_feat.npy\"))\n",
    "    text_feat  = np.load(os.path.join(src_dir, \"text_feat.npy\"))\n",
    "\n",
    "    print(f\"  • Multimodal feature shapes:\")\n",
    "    print(f\"    - Audio: {audio_feat.shape} ({audio_feat.dtype})\")\n",
    "    print(f\"    - Image: {image_feat.shape} ({image_feat.dtype})\")\n",
    "    print(f\"    - Text : {text_feat.shape} ({text_feat.dtype})\")\n",
    "\n",
    "    audio_tensor = torch.from_numpy(audio_feat.astype(np.float32))\n",
    "    image_tensor = torch.from_numpy(image_feat.astype(np.float32))\n",
    "    text_tensor  = torch.from_numpy(text_feat.astype(np.float32))\n",
    "\n",
    "    concat_np = np.concatenate([audio_feat.astype(np.float32), image_feat.astype(np.float32), text_feat.astype(np.float32)], axis=1)\n",
    "    concat_tensor = torch.from_numpy(concat_np)\n",
    "\n",
    "    modality_maps = {\n",
    "        \"visual_modality.pkl\": image_tensor,\n",
    "        \"textual_modality.pkl\": text_tensor,\n",
    "        \"audio_modality.pkl\": audio_tensor,\n",
    "        \"multimodal_concat.pkl\": concat_tensor\n",
    "    }\n",
    "\n",
    "    for pkl_name, tensor_data in modality_maps.items():\n",
    "        out_path = os.path.join(dst_dir, pkl_name)\n",
    "        with open(out_path, \"wb\") as f:\n",
    "            pickle.dump(tensor_data, f, protocol=pickle.HIGHEST_PROTOCOL)\n",
    "        size_mb = os.path.getsize(out_path) / (1024 * 1024)\n",
    "        print(f\"  [Đã sinh] {pkl_name}: {tensor_data.shape} ({size_mb:.2f} MB)\")\n",
    "\n",
    "    print(f\"✅ Hoàn tất chuyển đổi TikTok dataset sang chuẩn STAIR/FreeRec!\")\n",
    "\n",
    "def scan_and_prepare_tiktok():\n",
    "    target_processed = os.path.join(PROCESSED_ROOT, TARGET_FOLDER)\n",
    "    \n",
    "    # 1. Kiểm tra nếu đã có sẵn đầy đủ các tệp processed\n",
    "    for cand in [target_processed, os.path.join(DATA_ROOT, TARGET_FOLDER), os.path.join(LOCAL_PROCESSED, TARGET_FOLDER)]:\n",
    "        if os.path.exists(cand) and all(os.path.exists(os.path.join(cand, f)) for f in REQUIRED_PROCESSED_FILES):\n",
    "            print(f\"✅ Dữ liệu TikTok chuẩn FreeRec đã tồn tại sẵn tại: {cand}\")\n",
    "            bridge_directories(cand, TARGET_FOLDER)\n",
    "            return {'tiktok': target_processed}\n",
    "\n",
    "    # 2. Tìm kiếm trong /kaggle/input (hỗ trợ /kaggle/input/tiktok/tiktok, /kaggle/input/Tiktok/tiktok, ...)\n",
    "    print(\"🔍 Đang quét /kaggle/input để tìm kiếm tập dữ liệu TikTok...\")\n",
    "    input_base = '/kaggle/input'\n",
    "    raw_src = None\n",
    "    \n",
    "    for attempt in range(12):\n",
    "        if os.path.exists(input_base):\n",
    "            for root, dirs, files in os.walk(input_base):\n",
    "                # Nếu đã là dạng processed\n",
    "                if all(rf in files for rf in REQUIRED_PROCESSED_FILES):\n",
    "                    print(f\"  [TÌM THẤY DỮ LIỆU ĐÃ XỬ LÝ] {root}\")\n",
    "                    os.makedirs(target_processed, exist_ok=True)\n",
    "                    for f in files:\n",
    "                        shutil.copy2(os.path.join(root, f), os.path.join(target_processed, f))\n",
    "                    bridge_directories(target_processed, TARGET_FOLDER)\n",
    "                    return {'tiktok': target_processed}\n",
    "\n",
    "                # Nếu là dạng raw DiffMM (.pkl + .npy)\n",
    "                if all(rf in files for rf in RAW_FILES):\n",
    "                    raw_src = root\n",
    "                    print(f\"  [TÌM THẤY DỮ LIỆU RAW TIKTOK] {root}\")\n",
    "                    break\n",
    "            if raw_src:\n",
    "                break\n",
    "\n",
    "        # Kiểm tra dự phòng: tệp nén tiktok.zip trong repo\n",
    "        repo_zip = os.path.join(LOCAL_DATA, 'tiktok.zip')\n",
    "        if not raw_src and os.path.exists(repo_zip):\n",
    "            print(f\"📦 Phát hiện tệp nén {repo_zip} trong repository. Đang giải nén...\")\n",
    "            extract_dir = os.path.join(LOCAL_DATA, 'raw_tiktok')\n",
    "            with zipfile.ZipFile(repo_zip, 'r') as zf:\n",
    "                zf.extractall(extract_dir)\n",
    "            for root, dirs, files in os.walk(extract_dir):\n",
    "                if all(rf in files for rf in RAW_FILES):\n",
    "                    raw_src = root\n",
    "                    break\n",
    "\n",
    "        if raw_src:\n",
    "            break\n",
    "        print(f\"⏳ Dataset đang được tải về từ Kaggle... Đợi 5s (lần {attempt+1}/12)...\")\n",
    "        time.sleep(5)\n",
    "\n",
    "    if raw_src:\n",
    "        convert_raw_tiktok(raw_src, target_processed)\n",
    "        bridge_directories(target_processed, TARGET_FOLDER)\n",
    "        return {'tiktok': target_processed}\n",
    "    else:\n",
    "        print(\"❌ Không tìm thấy tập dữ liệu TikTok trong /kaggle/input hoặc trong repository!\")\n",
    "        return {}\n",
    "\n",
    "prepared_data = scan_and_prepare_tiktok()\n",
    "print(\"=\" * 75)\n",
    "p_dir = os.path.join(PROCESSED_ROOT, TARGET_FOLDER)\n",
    "ready_files = [f for f in REQUIRED_PROCESSED_FILES if os.path.exists(os.path.join(p_dir, f))]\n",
    "status = f\"✅ {len(ready_files)}/{len(REQUIRED_PROCESSED_FILES)} tệp chuẩn sẵn sàng\" if len(ready_files) == len(REQUIRED_PROCESSED_FILES) else \"❌ THIẾU\"\n",
    "print(f\"TỔNG KẾT DỮ LIỆU TIKTOK: {status} trong {p_dir}\")\n",
    "for rf in REQUIRED_PROCESSED_FILES:\n",
    "    fp = os.path.join(p_dir, rf)\n",
    "    if os.path.exists(fp):\n",
    "        sz = os.path.getsize(fp) / (1024 * 1024)\n",
    "        print(f\"  • {rf:25s}: {sz:.2f} MB\")\n",
    "print(\"=\" * 75)\n"
]
nb["cells"][4]["source"] = cell2_source

# Cell 8: Runner code (update run_training_v5_plus with batch_size support)
cell4_source = [
    "# Cell 4: Runner Huấn Luyện Tự Động (Hỗ trợ 4 Phương Pháp, Đa Phương Thức & GPU Telemetry)\n",
    "import subprocess, sys, os, time, re, threading\n",
    "\n",
    "try:\n",
    "    import pynvml\n",
    "    pynvml.nvmlInit()\n",
    "    HAS_NVML = True\n",
    "except Exception:\n",
    "    HAS_NVML = False\n",
    "\n",
    "def get_gpu_memory_used():\n",
    "    if not HAS_NVML:\n",
    "        return 0.0\n",
    "    try:\n",
    "        handle = pynvml.nvmlDeviceGetHandleByIndex(0)\n",
    "        info = pynvml.nvmlDeviceGetMemoryInfo(handle)\n",
    "        return info.used / (1024 ** 2)\n",
    "    except Exception:\n",
    "        return 0.0\n",
    "\n",
    "TRACKED_METRICS = ['Recall@10', 'Recall@20', 'NDCG@10', 'NDCG@20']\n",
    "\n",
    "def extract_best_test(log_path):\n",
    "    if not os.path.exists(log_path):\n",
    "        return None, {}\n",
    "\n",
    "    best_epoch = None\n",
    "    best_metrics = {}\n",
    "    with open(log_path, 'r', encoding='utf-8', errors='ignore') as f:\n",
    "        lines = f.readlines()\n",
    "\n",
    "    for line in lines:\n",
    "        m = re.search(r'NEW BEST MODEL @Epoch\\s+(\\d+)', line)\n",
    "        if m:\n",
    "            best_epoch = int(m.group(1))\n",
    "\n",
    "    in_official_test = False\n",
    "    for line in lines:\n",
    "        if 'ĐÁNH GIÁ CHÍNH THỨC TRÊN TẬP TEST' in line:\n",
    "            in_official_test = True\n",
    "            continue\n",
    "        if in_official_test:\n",
    "            for metric in TRACKED_METRICS:\n",
    "                m = re.search(rf'{re.escape(metric)}[\\s:]+([0-9.]+)', line)\n",
    "                if m and metric not in best_metrics:\n",
    "                    best_metrics[metric] = float(m.group(1))\n",
    "            if len(best_metrics) >= len(TRACKED_METRICS):\n",
    "                break\n",
    "\n",
    "    if not best_metrics:\n",
    "        test_section = False\n",
    "        for line in reversed(lines):\n",
    "            if 'Evaluation (test)' in line or 'Testing' in line:\n",
    "                test_section = True\n",
    "            if test_section:\n",
    "                for metric in TRACKED_METRICS:\n",
    "                    m = re.search(rf'{re.escape(metric)}[\\s:]+([0-9.]+)', line)\n",
    "                    if m and metric not in best_metrics:\n",
    "                        best_metrics[metric] = float(m.group(1))\n",
    "                if len(best_metrics) >= len(TRACKED_METRICS):\n",
    "                    break\n",
    "\n",
    "    return best_epoch, best_metrics\n",
    "\n",
    "def run_training_v5_plus(\n",
    "    key, yaml_cfg, data_root, log_path,\n",
    "    method='v5_plus',\n",
    "    epochs=500,\n",
    "    embedding_dim=256,\n",
    "    lr_warmup_epochs=15,\n",
    "    min_lr=1e-6,\n",
    "    patience=30,\n",
    "    tau=0.20, alpha_dir=0.50, eps=0.08, tau_thresh=0.85,\n",
    "    lambda_cl=0.010, gamma_h=0.15, warmup_epochs=50,\n",
    "    **kwargs\n",
    "):\n",
    "    print('=' * 85)\n",
    "    print(f'🚀 BẮT ĐẦU HUẤN LUYỆN: {key.upper()} | METHOD: [{method.upper()}] | DIM: [{embedding_dim}] | EPOCHS: [{epochs}]')\n",
    "    print(f'  * Dataset Key         : {key}')\n",
    "    print(f'  * Method              : {method}')\n",
    "    print(f'  * Embedding Dim       : {embedding_dim}')\n",
    "    print(f'  * Max Epochs          : {epochs}')\n",
    "    print(f'  * LR Cosine Warmup    : {lr_warmup_epochs} eps -> Cosine Decay (min_lr: {min_lr})')\n",
    "    print(f'  * Early Stop Patience : {patience} eps')\n",
    "    print(f'  * Target Metric       : NDCG@20 (N@20)')\n",
    "    print(f'  * Log Path            : {log_path}')\n",
    "    print('=' * 85)\n",
    "\n",
    "    os.makedirs(os.path.dirname(log_path), exist_ok=True)\n",
    "    t0 = time.time()\n",
    "    runner_py = '/kaggle/working/STAIR-Enhanced/main_stair_ne_nlgcl_v5_plus.py'\n",
    "    if not os.path.exists(runner_py):\n",
    "        runner_py = 'main_stair_ne_nlgcl_v5_plus.py'\n",
    "\n",
    "    cmd = [\n",
    "        sys.executable, runner_py,\n",
    "        '--config',           yaml_cfg,\n",
    "        '--root',             data_root,\n",
    "        '--method',           method,\n",
    "        '--epochs',           str(epochs),\n",
    "        '--embedding-dim',    str(embedding_dim),\n",
    "        '--lr-warmup-epochs', str(lr_warmup_epochs),\n",
    "        '--min-lr',           str(min_lr),\n",
    "        '--patience',         str(patience),\n",
    "        '--tau',              str(tau),\n",
    "        '--alpha-dir',        str(alpha_dir),\n",
    "        '--eps',              str(eps),\n",
    "        '--tau-thresh',       str(tau_thresh),\n",
    "        '--lambda-cl',        str(lambda_cl),\n",
    "        '--gamma-h',          str(gamma_h),\n",
    "        '--warmup-epochs',    str(warmup_epochs),\n",
    "    ]\n",
    "    if 'batch_size' in kwargs:\n",
    "        cmd.extend(['--batch-size', str(kwargs['batch_size'])])\n",
    "\n",
    "    with open(log_path, 'w', encoding='utf-8') as f:\n",
    "        proc = subprocess.Popen(\n",
    "            cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,\n",
    "            text=True, bufsize=1, universal_newlines=True\n",
    "        )\n",
    "        for line in proc.stdout:\n",
    "            sys.stdout.write(line)\n",
    "            sys.stdout.flush()\n",
    "            f.write(line)\n",
    "            f.flush()\n",
    "        proc.wait()\n",
    "\n",
    "    elapsed = time.time() - t0\n",
    "    print('=' * 85)\n",
    "    if proc.returncode != 0:\n",
    "        print(f'❌ [THẤT BẠI] Quá trình huấn luyện {key.upper()} gặp lỗi (Exit Code: {proc.returncode})!')\n",
    "    else:\n",
    "        print(f'✅ [HOÀN TẤT] Huấn luyện {key.upper()} ({method}) thành công trong {elapsed/60:.2f} phút ({elapsed:.1f}s)!')\n",
    "\n",
    "    best_ep, metrics = extract_best_test(log_path)\n",
    "    print(f'  * Checkpoint tối ưu : Epoch {best_ep}')\n",
    "    for m, val in metrics.items():\n",
    "        print(f'  * {m:12s}: {val:.4f}')\n",
    "    print('=' * 85)\n"
]
nb["cells"][8]["source"] = cell4_source

# Cell 9: Markdown intro for Configs
nb["cells"][9]["source"] = [
    "## Cell 5 📋 Cấu hình Siêu tham số DCD-Gated cho TikTok\n",
    "Thiết lập tham số tối ưu cho **TikTok (Tri-modal Micro-Video - 9,308 Users, 6,710 Items)**:\n",
    "- `embedding_dim`: 256 (Gấp 4 lần Baseline 64D nhằm nâng cao dung lượng biểu diễn đa giác quan).\n",
    "- `batch_size`: 2048 (Tối ưu thông lượng và bộ nhớ trên GPU T4).\n",
    "- `lr_warmup_epochs`: 15 eps -> Cosine Annealing về 1e-6.\n",
    "- `patience`: 30 epochs dừng sớm khi không cải thiện `NDCG@20`.\n",
    "- `weight_decay`: 0.1, `tau`: 0.20, `eps`: 0.08, `tau_thresh`: 0.85, `lambda_cl`: 0.010, `gamma_h`: 0.15.\n"
]

# Cell 10: Configs for TikTok
cell5_source = [
    "# Cell 5: Cấu hình Siêu tham số cho TikTok (Dim 256, Cosine LR, Patience 30, Epochs 500)\n",
    "import os\n",
    "\n",
    "os.makedirs('/kaggle/working/logs/breakthrough', exist_ok=True)\n",
    "\n",
    "V5_PLUS_CONFIGS = {\n",
    "    'tiktok': {\n",
    "        'yaml':              '/kaggle/working/STAIR-Enhanced/configs/tiktok_MMRec.yaml',\n",
    "        'embedding_dim':     256,\n",
    "        'batch_size':        2048,\n",
    "        'epochs':            500,\n",
    "        'lr_warmup_epochs':  15,\n",
    "        'min_lr':            1e-6,\n",
    "        'patience':          30,\n",
    "        'weight_decay':      0.1,\n",
    "        'tau':               0.20,\n",
    "        'alpha_dir':         0.50,\n",
    "        'eps':               0.08,\n",
    "        'tau_thresh':        0.85,\n",
    "        'lambda_cl':         0.010,\n",
    "        'gamma_h':           0.15,\n",
    "        'warmup_epochs':     50,\n",
    "    },\n",
    "}\n",
    "\n",
    "print('=' * 85)\n",
    "print('✅ CẤU HÌNH THỰC NGHIỆM CHO TIKTOK ĐÃ SẴN SÀNG (DIM=256, CHECKPOINT=NDCG@20):')\n",
    "for k, v in V5_PLUS_CONFIGS.items():\n",
    "    print(f\"  • [{k.upper()}]: Epochs={v['epochs']}, Dim={v['embedding_dim']}, BatchSize={v['batch_size']}, LR Warmup={v['lr_warmup_epochs']} eps, Patience={v['patience']} eps, Lambda_CL={v['lambda_cl']}\")\n",
    "print('=' * 85)\n"
]
nb["cells"][10]["source"] = cell5_source

# Cell 11: Markdown intro for Training
nb["cells"][11]["source"] = [
    "## Cell 6 🏋️ Huấn luyện DCD-Gated trên TikTok\n",
    "Chạy huấn luyện chính thức với phương pháp đột phá **DCD-Gated** (`SELECTED_METHOD = 'dcd_gated'`).\n",
    "Hệ thống sẽ tự động giám sát checkpoint theo `NDCG@20` cao nhất, kích hoạt dừng sớm sau 30 epochs nếu hội tụ, và đánh giá toàn diện trên tập kiểm thử độc lập (TEST)."
]

# Cell 12: Training Execution on TikTok
cell6_source = [
    "# Cell 6: Huấn luyện trên TikTok\n",
    "# Tùy chọn method: 'dcd_gated' (Đột phá), 'dan_tans' (Hướng 1), 'appnp_crossmodal' (Hướng 3), 'v5_plus' (gốc)\n",
    "SELECTED_METHOD = 'dcd_gated' # <--- Phương pháp đột phá đã lập kỷ lục trên Sports!\n",
    "\n",
    "DATA_ROOT = '/kaggle/data'\n",
    "\n",
    "if 'tiktok' in prepared_data or (os.path.exists('/kaggle/data/Processed/tiktok') and len(os.listdir('/kaggle/data/Processed/tiktok')) >= 6):\n",
    "    cfg_t = V5_PLUS_CONFIGS['tiktok']\n",
    "    log_p = f\"/kaggle/working/logs/breakthrough/tiktok_{SELECTED_METHOD}_dim256.log\"\n",
    "    run_training_v5_plus(\n",
    "        key='tiktok',\n",
    "        yaml_cfg=cfg_t['yaml'],\n",
    "        data_root=DATA_ROOT,\n",
    "        log_path=log_p,\n",
    "        method=SELECTED_METHOD,\n",
    "        **{k: v for k, v in cfg_t.items() if k != 'yaml'}\n",
    "    )\n",
    "else:\n",
    "    print('⚠️ Bỏ qua TikTok do thiếu dữ liệu trong /kaggle/input.')\n"
]
nb["cells"][12]["source"] = cell6_source

# Cell 13: Markdown intro for PrettyTable
nb["cells"][13]["source"] = [
    "## Cell 7 📊 Bảng Tổng Kết Kết Quả Thực Nghiệm (TikTok)\n",
    "Bảng tổng hợp đối sánh 4 chỉ số khoa học: **Recall@10, Recall@20, NDCG@10, NDCG@20** và mức tăng trưởng trọng tâm **NDCG@20 (Δ vs Baseline N@20)** so với mốc STAIR Baseline gốc (64D)."
]

# Cell 14: PrettyTable for TikTok
cell7_source = [
    "# Cell 7: Bảng tổng kết kết quả thực nghiệm TikTok\n",
    "import os, glob\n",
    "from prettytable import PrettyTable\n",
    "\n",
    "BASELINE = {\n",
    "    'tiktok': {'Recall@10': 0.0558, 'Recall@20': 0.0799, 'NDCG@10': 0.0292, 'NDCG@20': 0.0352},\n",
    "}\n",
    "\n",
    "table = PrettyTable()\n",
    "table.field_names = ['Tập dữ liệu', 'Phương pháp', 'Recall@10', 'Recall@20', 'NDCG@10', 'NDCG@20', 'Δ vs Baseline N@20']\n",
    "\n",
    "for ds in ['tiktok']:\n",
    "    bl = BASELINE[ds]\n",
    "    table.add_row([ds.upper(), 'STAIR Baseline (64D)', f\"{bl['Recall@10']:.4f}\", f\"{bl['Recall@20']:.4f}\", f\"{bl['NDCG@10']:.4f}\", f\"{bl['NDCG@20']:.4f}\", '-'])\n",
    "    \n",
    "    log_files = glob.glob(f\"/kaggle/working/logs/breakthrough/{ds}_*.log\")\n",
    "    for lf in log_files:\n",
    "        ep, m = extract_best_test(lf)\n",
    "        if m and len(m) >= 4:\n",
    "            tag = os.path.basename(lf).replace(f\"{ds}_\", \"\").replace(\".log\", \"\")\n",
    "            gain = (m['NDCG@20'] - bl['NDCG@20']) / bl['NDCG@20'] * 100\n",
    "            sign = '+' if gain >= 0 else ''\n",
    "            table.add_row([ds.upper(), f\"★ {tag} (@Ep{ep})\", f\"{m['Recall@10']:.4f}\", f\"{m['Recall@20']:.4f}\", f\"{m['NDCG@10']:.4f}\", f\"{m['NDCG@20']:.4f}\", f\"{sign}{gain:.2f}%\"])\n",
    "\n",
    "print(table)\n"
]
nb["cells"][14]["source"] = cell7_source

out_path = r"d:\STAIR-Enhanced\notebook\stair_tiktok.ipynb"
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"[OK] Successfully generated notebook for TikTok: {out_path}")
