# -*- coding: utf-8 -*-
"""
scripts/update_v5_plus_notebook.py
==================================
Updates notebook/P3/stair_ne_nlgcl_v5_plus.ipynb:
1. Target ONLY Amazon Baby & Amazon Sports (Electronics & TikTok disabled).
2. Set embedding_dim = 256 for both datasets.
3. Cosine LR Warmup (15 epochs) + Annealing.
4. Early Stopping Patience = 30 epochs without NDCG@20 improvement.
5. Max Epochs = 500 (reduced from 1000).
6. Removed composite metric averaging: focus 100% on NDCG@20 for checkpoint selection and early stopping.
7. Support all 4 methods: v5_plus, dan_tans, dcd_gated, appnp_crossmodal.
8. Embed updated python modules into Cell 1.
"""
import json
import os

with open(r"d:\STAIR-Enhanced\models\stair_breakthrough.py", "r", encoding="utf-8") as f:
    breakthrough_model_code = f.read()

with open(r"d:\STAIR-Enhanced\models\stair_ne_nlgcl_v5_plus.py", "r", encoding="utf-8") as f:
    v5_plus_model_code = f.read()

with open(r"d:\STAIR-Enhanced\main_stair_ne_nlgcl_v5_plus.py", "r", encoding="utf-8") as f:
    runner_code = f.read()

notebook_path = r"d:\STAIR-Enhanced\notebook\P3\stair_ne_nlgcl_v5_plus.ipynb"
with open(notebook_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

# 1. Update Title / Markdown Header (Cell 0)
nb["cells"][0]["source"] = [
    "# 🚀 GIAI ĐOẠN 3: STAIR-NE-NLGCL v5+ (v3-REFINED) & BỘ 3 PHƯƠNG PHÁP ĐỘT PHÁ\n",
    "## 🏆 Embedding Dim = 256 | Cosine Warmup LR (15 eps) | Patience = 30 | Checkpoint: NDCG@20 (500 eps)\n",
    "*(Tập trung độc quyền trên 2 tập dữ liệu: **Amazon Baby** & **Amazon Sports**; Đã tắt hoàn toàn Electronics và TikTok)*\n",
    "---\n",
    "### 🎯 4 PHƯƠNG PHÁP CÓ THỂ CHỌN KHI HUẤN LUYỆN (`method`):\n",
    "1. **`v5_plus` (Mốc đối chứng SOTA v3-Refined):**\n",
    "   - 100% Direct Gradient Flow (Không Projection Head).\n",
    "   - Nhiễu phổ bảo toàn hướng tuyệt đối $|\\boldsymbol{\\eta}| \\ge 0$.\n",
    "   - Phạt mẫu âm tuyến tính Linear HANS: $\\psi(s) = 1.0 + 0.15 \\max(0, s)$.\n",
    "   - Lọc âm giả ngưỡng cứng Hard MFNA $\\mathbb{I}(s \\le 0.85)$ và $\\lambda_{cl}=0.010$ cố định (warmup 50 eps).\n",
    "\n",
    "2. **`dan_tans` (Phương pháp 1: Degree-Aware Noise & Topology-Aware Negative Scheduling):**\n",
    "   - Head items nhận nhiễu lớn hơn để chống over-smoothing; Tail items nhận nhiễu nhỏ để bảo tồn biểu diễn.\n",
    "   - Tăng hệ số phạt mẫu âm $\\gamma_h(d_i)$ đối với các item đuôi dài để định hình biên quyết định sắc nét.\n",
    "\n",
    "3. **`dcd_gated` (Phương pháp 2: Dual-Consensus Denoising & Gated Residuals):**\n",
    "   - Làm dày cạnh tin cậy dựa trên độ đồng thuận kép giữa hành vi Ochiai và đặc trưng Modal ($S_{co} \\odot S_{modal}$).\n",
    "   - Van Gating động đóng lại khi cạnh ảo bị nhiễu, an toàn 100%.\n",
    "\n",
    "4. **`appnp_crossmodal` (Phương pháp 3: APPNP-Restart Propagation & Cross-Modal CL):**\n",
    "   - Hệ số restart $\\alpha=0.15$ bảo tồn biểu diễn gốc $H^{(0)}$ xuyên suốt tích chập.\n",
    "   - Đối chiếu chéo User <-> Modal nội dung cho Cold-start items.\n",
    "---\n",
    "### 📌 4 TRỤ CỘT TỐI ƯU SIÊU THAM SỐ:\n",
    "* **Max Epochs:** `500` epochs (tối ưu hóa hội tụ, loại bỏ chạy thừa quá mức).\n",
    "* **Embedding Dimension:** `256` (tăng gấp 4 lần so với 64D).\n",
    "* **Cosine Warmup LR:** 15 epoch đầu tăng tuyến tính từ `1e-6` -> `1e-3`, sau đó decay theo cosine về `1e-6`.\n",
    "* **Early Stopping & Checkpoint:** `30` epochs patience, tập trung độc quyền vào tối ưu hóa **`NDCG@20`** (bỏ trung bình 4 chỉ số).\n"
]

# 2. Update Cell 1: Environment & Sync (Code Cell 1 -> nb['cells'][2])
cell1_source = [
    "# Cell 1: Môi trường, Dependencies & Đồng bộ STAIR-Enhanced\n",
    "import os, shutil, subprocess, sys\n",
    "\n",
    "STAIR_DIR = '/kaggle/working/STAIR-Enhanced'\n",
    "os.chdir('/kaggle/working')\n",
    "\n",
    "# 1. Luôn clone hoặc đồng bộ cưỡng bức repository mới nhất từ origin/main\n",
    "if os.path.exists(STAIR_DIR):\n",
    "    print(\"Thư mục STAIR-Enhanced đã tồn tại. Đang đồng bộ cưỡng bức mã nguồn mới nhất...\")\n",
    "    try:\n",
    "        subprocess.run(['git', '-C', STAIR_DIR, 'fetch', 'origin', 'main'], check=True)\n",
    "        subprocess.run(['git', '-C', STAIR_DIR, 'reset', '--hard', 'origin/main'], check=True)\n",
    "        print(\"✅ Đã reset về commit mới nhất của origin/main.\")\n",
    "    except Exception as e:\n",
    "        print(f\"Lỗi git fetch/reset ({e}), đang làm sạch và clone lại từ đầu...\")\n",
    "        shutil.rmtree(STAIR_DIR, ignore_errors=True)\n",
    "\n",
    "if not os.path.exists(STAIR_DIR):\n",
    "    print(\"Cloning STAIR-Enhanced repository (branch main)...\" )\n",
    "    subprocess.run([\n",
    "        'git', 'clone', '--depth', '1',\n",
    "        'https://github.com/HenryBui777/STAIR-Enhanced.git', STAIR_DIR\n",
    "    ], check=True)\n",
    "\n",
    "for p in [STAIR_DIR, '/kaggle/working']:\n",
    "    if p not in sys.path:\n",
    "        sys.path.insert(0, p)\n",
    "\n",
    "if os.path.exists(STAIR_DIR):\n",
    "    os.chdir(STAIR_DIR)\n",
    "\n",
    "# Ghi đảm bảo module breakthrough, v5_plus và runner tồn tại trên đĩa\n",
    "os.makedirs(os.path.join(STAIR_DIR, 'models'), exist_ok=True)\n",
    "with open(os.path.join(STAIR_DIR, 'models', 'stair_breakthrough.py'), 'w', encoding='utf-8') as f:\n",
    f"    f.write({repr(breakthrough_model_code)})\n",
    "with open(os.path.join(STAIR_DIR, 'models', 'stair_ne_nlgcl_v5_plus.py'), 'w', encoding='utf-8') as f:\n",
    f"    f.write({repr(v5_plus_model_code)})\n",
    "with open(os.path.join(STAIR_DIR, 'main_stair_ne_nlgcl_v5_plus.py'), 'w', encoding='utf-8') as f:\n",
    f"    f.write({repr(runner_code)})\n",
    "\n",
    "# Xóa cache module để kernel luôn nạp phiên bản mới nhất từ đĩa\n",
    "for mod_name in list(sys.modules.keys()):\n",
    "    if 'stair_ne_nlgcl' in mod_name or 'stair_breakthrough' in mod_name:\n",
    "        sys.modules.pop(mod_name, None)\n",
    "\n",
    "# 2. Cài đặt các gói phụ thuộc bắt buộc (torch_geometric, freerec, torchdata, nvidia-ml-py, prettytable)\n",
    "print(\"📦 Cài đặt dependencies (torchdata, torch_geometric, freerec, nvidia-ml-py, prettytable)...\")\n",
    "subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '--no-deps', 'torchdata==0.7.1'], check=False)\n",
    "subprocess.run([\n",
    "    sys.executable, '-m', 'pip', 'install', '-q',\n",
    "    'torch_geometric', 'freerec==0.8.5', 'nvidia-ml-py', 'prettytable', 'matplotlib', 'pyyaml', 'seaborn'\n",
    "], check=True)\n",
    "\n",
    "# 3. Kaggle TorchData compatibility shims cho FreeRec (PyTorch 2.x & Python 3.10+)\n",
    "import types\n",
    "import torch.utils.data\n",
    "\n",
    "try:\n",
    "    import torchdata\n",
    "    import torchdata.datapipes as dp\n",
    "except Exception:\n",
    "    dp = None\n",
    "\n",
    "if dp is None or 'torchdata.datapipes' not in sys.modules:\n",
    "    if 'torchdata' not in sys.modules:\n",
    "        td = types.ModuleType('torchdata')\n",
    "        sys.modules['torchdata'] = td\n",
    "    else:\n",
    "        td = sys.modules['torchdata']\n",
    "    dp = types.ModuleType('torchdata.datapipes')\n",
    "    td.datapipes = dp\n",
    "    sys.modules['torchdata.datapipes'] = dp\n",
    "\n",
    "if not hasattr(dp, 'iter'):\n",
    "    iter_mod = types.ModuleType('torchdata.datapipes.iter')\n",
    "    dp.iter = iter_mod\n",
    "    sys.modules['torchdata.datapipes.iter'] = iter_mod\n",
    "if not hasattr(dp.iter, 'IterDataPipe'):\n",
    "    class IterDataPipe(torch.utils.data.IterableDataset):\n",
    "        def __iter__(self): return iter([])\n",
    "    dp.iter.IterDataPipe = IterDataPipe\n",
    "\n",
    "if not hasattr(dp, 'map'):\n",
    "    map_mod = types.ModuleType('torchdata.datapipes.map')\n",
    "    dp.map = map_mod\n",
    "    sys.modules['torchdata.datapipes.map'] = map_mod\n",
    "if not hasattr(dp.map, 'MapDataPipe'):\n",
    "    class MapDataPipe(torch.utils.data.Dataset):\n",
    "        def __getitem__(self, idx): raise NotImplementedError\n",
    "        def __len__(self): return 0\n",
    "    dp.map.MapDataPipe = MapDataPipe\n",
    "\n",
    "if not hasattr(dp, 'functional_datapipe'):\n",
    "    def functional_datapipe(name, enable_df_datapipes_support=False):\n",
    "        def decorator(cls):\n",
    "            def method(self, *args, **kwargs): return cls(self, *args, **kwargs)\n",
    "            if hasattr(dp, 'iter') and hasattr(dp.iter, 'IterDataPipe'): setattr(dp.iter.IterDataPipe, name, method)\n",
    "            if hasattr(dp, 'map') and hasattr(dp.map, 'MapDataPipe'): setattr(dp.map.MapDataPipe, name, method)\n",
    "            return cls\n",
    "        return decorator\n",
    "    dp.functional_datapipe = functional_datapipe\n",
    "\n",
    "print(\"✅ Môi trường STAIR-Enhanced & Dependencies đã hoàn tất sẵn sàng!\")\n"
]
nb["cells"][2]["source"] = cell1_source

# 3. Update Cell 4: Runner Function (Code Cell 4 -> nb['cells'][8])
cell4_source = [
    "# Cell 4: Runner Huấn Luyện Tự Động (Hỗ trợ 4 Phương Pháp, Dim 256, Cosine LR, Patience 30, Epochs 500)\n",
    "import subprocess, sys, os, time, re, threading\n",
    "\n",
    "TRACKED_METRICS = ['Recall@10', 'Recall@20', 'NDCG@10', 'NDCG@20']\n",
    "vram_profile = {}\n",
    "\n",
    "def extract_best_test(log_path):\n",
    "    if not os.path.exists(log_path):\n",
    "        return None, {}\n",
    "    with open(log_path, 'r', encoding='utf-8', errors='ignore') as f:\n",
    "        content = f.read()\n",
    "        lines = content.splitlines()\n",
    "\n",
    "    best_epoch = None\n",
    "    best_metrics = {}\n",
    "    ep_matches = re.findall(r'(?:Load best model @Epoch|TEST @Epoch:|Best @Epoch:?)\\s*(\\d+)', content, re.IGNORECASE)\n",
    "    if ep_matches:\n",
    "        best_epoch = int(ep_matches[-1])\n",
    "    else:\n",
    "        for line in reversed(lines):\n",
    "            m = re.search(r'Epoch:\\s*(\\d+)', line)\n",
    "            if m:\n",
    "                best_epoch = int(m.group(1))\n",
    "                break\n",
    "\n",
    "    for line in reversed(lines):\n",
    "        if 'TEST' in line and 'Avg:' in line:\n",
    "            for metric in TRACKED_METRICS:\n",
    "                m = re.search(rf'{metric}\\s*Avg:\\s*([0-9.]+)', line, re.IGNORECASE)\n",
    "                if m:\n",
    "                    best_metrics[metric] = float(m.group(1))\n",
    "            if len(best_metrics) >= len(TRACKED_METRICS):\n",
    "                break\n",
    "\n",
    "    if len(best_metrics) < len(TRACKED_METRICS):\n",
    "        for line in reversed(lines):\n",
    "            if 'VALID' in line and 'Avg:' in line:\n",
    "                for metric in TRACKED_METRICS:\n",
    "                    m = re.search(rf'{metric}\\s*Avg:\\s*([0-9.]+)', line, re.IGNORECASE)\n",
    "                    if m and metric not in best_metrics:\n",
    "                        best_metrics[metric] = float(m.group(1))\n",
    "                if len(best_metrics) >= len(TRACKED_METRICS):\n",
    "                    break\n",
    "\n",
    "    return best_epoch, best_metrics\n",
    "\n",
    "def run_training_v5_plus(\n",
    "    key, yaml_cfg, data_root, log_path,\n",
    "    method='v5_plus',\n",
    "    epochs=500,\n",
    "    embedding_dim=256,\n",
    "    lr_warmup_epochs=15,\n",
    "    min_lr=1e-6,\n",
    "    patience=30,\n",
    "    tau=0.20, alpha_dir=0.50, eps=0.08, tau_thresh=0.85,\n",
    "    lambda_cl=0.010, gamma_h=0.15, warmup_epochs=50,\n",
    "    **kwargs\n",
    "):\n",
    "    print('=' * 85)\n",
    "    print(f'🚀 BẮT ĐẦU HUẤN LUYỆN: {key.upper()} | METHOD: [{method.upper()}] | DIM: [{embedding_dim}] | EPOCHS: [{epochs}]')\n",
    "    print(f'  * Dataset Key         : {key}')\n",
    "    print(f'  * Method              : {method}')\n",
    "    print(f'  * Embedding Dim       : {embedding_dim}')\n",
    "    print(f'  * Max Epochs          : {epochs}')\n",
    "    print(f'  * LR Cosine Warmup    : {lr_warmup_epochs} eps -> Cosine Decay (min_lr: {min_lr})')\n",
    "    print(f'  * Early Stop Patience : {patience} eps')\n",
    "    print(f'  * Target Metric       : NDCG@20 (N@20)')\n",
    "    print(f'  * Log Path            : {log_path}')\n",
    "    print('=' * 85)\n",
    "\n",
    "    os.makedirs(os.path.dirname(log_path), exist_ok=True)\n",
    "    t0 = time.time()\n",
    "    runner_py = '/kaggle/working/STAIR-Enhanced/main_stair_ne_nlgcl_v5_plus.py'\n",
    "    if not os.path.exists(runner_py):\n",
    "        runner_py = 'main_stair_ne_nlgcl_v5_plus.py'\n",
    "\n",
    "    cmd = [\n",
    "        sys.executable, runner_py,\n",
    "        '--config',           yaml_cfg,\n",
    "        '--root',             data_root,\n",
    "        '--method',           method,\n",
    "        '--epochs',           str(epochs),\n",
    "        '--embedding-dim',    str(embedding_dim),\n",
    "        '--lr-warmup-epochs', str(lr_warmup_epochs),\n",
    "        '--min-lr',           str(min_lr),\n",
    "        '--patience',         str(patience),\n",
    "        '--tau',              str(tau),\n",
    "        '--alpha-dir',        str(alpha_dir),\n",
    "        '--eps',              str(eps),\n",
    "        '--tau-thresh',       str(tau_thresh),\n",
    "        '--lambda-cl',        str(lambda_cl),\n",
    "        '--gamma-h',          str(gamma_h),\n",
    "        '--warmup-epochs',    str(warmup_epochs),\n",
    "    ]\n",
    "\n",
    "    with open(log_path, 'w', encoding='utf-8') as f:\n",
    "        proc = subprocess.Popen(\n",
    "            cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,\n",
    "            text=True, bufsize=1, universal_newlines=True\n",
    "        )\n",
    "        for line in proc.stdout:\n",
    "            sys.stdout.write(line)\n",
    "            sys.stdout.flush()\n",
    "            f.write(line)\n",
    "            f.flush()\n",
    "        proc.wait()\n",
    "\n",
    "    elapsed = time.time() - t0\n",
    "    print('=' * 85)\n",
    "    if proc.returncode != 0:\n",
    "        print(f'❌ [THẤT BẠI] Quá trình huấn luyện {key.upper()} gặp lỗi (Exit Code: {proc.returncode})!')\n",
    "    else:\n",
    "        print(f'✅ [HOÀN TẤT] Huấn luyện {key.upper()} ({method}) thành công trong {elapsed/60:.2f} phút ({elapsed:.1f}s)!')\n",
    "\n",
    "    best_ep, metrics = extract_best_test(log_path)\n",
    "    print(f'  * Checkpoint tối ưu : Epoch {best_ep}')\n",
    "    for m, val in metrics.items():\n",
    "        print(f'  * {m:12s}: {val:.4f}')\n",
    "    print('=' * 85)\n"
]
nb["cells"][8]["source"] = cell4_source

# 4. Update Cell 5: Hyperparameters (Code Cell 5 -> nb['cells'][10])
cell5_source = [
    "# Cell 5: Cấu hình Siêu tham số (Chỉ cho Baby & Sports: Dim 256, Cosine LR, Patience 30, Epochs 500)\n",
    "import os\n",
    "\n",
    "os.makedirs('/kaggle/working/logs/breakthrough', exist_ok=True)\n",
    "\n",
    "V5_PLUS_CONFIGS = {\n",
    "    'baby': {\n",
    "        'yaml':              '/kaggle/working/STAIR-Enhanced/configs/Amazon2014Baby_550_MMRec.yaml',\n",
    "        'embedding_dim':     256,\n",
    "        'epochs':            500,\n",
    "        'lr_warmup_epochs':  15,\n",
    "        'min_lr':            1e-6,\n",
    "        'patience':          30,\n",
    "        'weight_decay':      0.3,\n",
    "        'tau':               0.20,\n",
    "        'alpha_dir':         0.50,\n",
    "        'eps':               0.08,\n",
    "        'tau_thresh':        0.85,\n",
    "        'lambda_cl':         0.010,\n",
    "        'gamma_h':           0.15,\n",
    "        'warmup_epochs':     50,\n",
    "    },\n",
    "    'sports': {\n",
    "        'yaml':              '/kaggle/working/STAIR-Enhanced/configs/Amazon2014Sports_550_MMRec.yaml',\n",
    "        'embedding_dim':     256,\n",
    "        'epochs':            500,\n",
    "        'lr_warmup_epochs':  15,\n",
    "        'min_lr':            1e-6,\n",
    "        'patience':          30,\n",
    "        'weight_decay':      0.1,\n",
    "        'tau':               0.20,\n",
    "        'alpha_dir':         0.50,\n",
    "        'eps':               0.08,\n",
    "        'tau_thresh':        0.85,\n",
    "        'lambda_cl':         0.010,\n",
    "        'gamma_h':           0.15,\n",
    "        'warmup_epochs':     50,\n",
    "    },\n",
    "}\n",
    "\n",
    "print('=' * 85)\n",
    "print('✅ CẤU HÌNH THỰC NGHIỆM ĐÃ SẴN SÀNG (EPOCHS = 500, CHECKPOINT = NDCG@20):')\n",
    "for k, v in V5_PLUS_CONFIGS.items():\n",
    "    print(f\"  • [{k.upper()}]: Epochs={v['epochs']}, Dim={v['embedding_dim']}, LR Warmup={v['lr_warmup_epochs']} eps, Patience={v['patience']} eps, Lambda_CL={v['lambda_cl']}\")\n",
    "print('=' * 85)\n"
]
nb["cells"][10]["source"] = cell5_source

# 5. Update Cell 7: Markdown Header (Markdown Cell 7 -> nb['cells'][13])
nb["cells"][13]["source"] = [
    "## Cell 7 📊 Bảng Tổng Kết Kết Quả Thực Nghiệm (Baby & Sports)\n",
    "Bảng tổng hợp đối sánh 4 chỉ số khoa học: **Recall@10, Recall@20, NDCG@10, NDCG@20** và mức cải thiện trọng tâm **NDCG@20 (Δ vs v5 N@20)** giữa Baseline, SOTA v5 và Phương pháp cải tiến mới."
]

# 6. Update Cell 7: PrettyTable Code (Code Cell 7 -> nb['cells'][14])
nb["cells"][14]["source"] = [
    "# Cell 7: Bảng tổng kết kết quả thực nghiệm Baby & Sports\n",
    "import os, glob\n",
    "from prettytable import PrettyTable\n",
    "\n",
    "BASELINE = {\n",
    "    'baby':   {'Recall@10': 0.0674, 'Recall@20': 0.1042, 'NDCG@10': 0.0359, 'NDCG@20': 0.0454},\n",
    "    'sports': {'Recall@10': 0.0743, 'Recall@20': 0.1111, 'NDCG@10': 0.0405, 'NDCG@20': 0.0500},\n",
    "}\n",
    "V5_RESULTS = {\n",
    "    'baby':   {'Recall@10': 0.0669, 'Recall@20': 0.1027, 'NDCG@10': 0.0362, 'NDCG@20': 0.0454},\n",
    "    'sports': {'Recall@10': 0.0753, 'Recall@20': 0.1113, 'NDCG@10': 0.0415, 'NDCG@20': 0.0508},\n",
    "}\n",
    "\n",
    "table = PrettyTable()\n",
    "table.field_names = ['Tập dữ liệu', 'Phương pháp', 'Recall@10', 'Recall@20', 'NDCG@10', 'NDCG@20', 'Δ vs v5 N@20']\n",
    "\n",
    "for ds in ['baby', 'sports']:\n",
    "    # Mốc chuẩn Baseline\n",
    "    bl = BASELINE[ds]\n",
    "    table.add_row([ds.upper(), 'STAIR Baseline (64D)', f\"{bl['Recall@10']:.4f}\", f\"{bl['Recall@20']:.4f}\", f\"{bl['NDCG@10']:.4f}\", f\"{bl['NDCG@20']:.4f}\", '-'])\n",
    "    \n",
    "    # Mốc chuẩn v5\n",
    "    v5 = V5_RESULTS[ds]\n",
    "    table.add_row([ds.upper(), 'STAIR v5 SOTA (64D)', f\"{v5['Recall@10']:.4f}\", f\"{v5['Recall@20']:.4f}\", f\"{v5['NDCG@10']:.4f}\", f\"{v5['NDCG@20']:.4f}\", '0.00%'])\n",
    "    \n",
    "    # Các log thực nghiệm mới trong logs/breakthrough\n",
    "    log_files = glob.glob(f\"/kaggle/working/logs/breakthrough/{ds}_*.log\")\n",
    "    for lf in log_files:\n",
    "        ep, m = extract_best_test(lf)\n",
    "        if m and len(m) >= 4:\n",
    "            tag = os.path.basename(lf).replace(f\"{ds}_\", \"\").replace(\".log\", \"\")\n",
    "            gain = (m['NDCG@20'] - v5['NDCG@20']) / v5['NDCG@20'] * 100\n",
    "            sign = '+' if gain >= 0 else ''\n",
    "            table.add_row([ds.upper(), f\"★ {tag} (@Ep{ep})\", f\"{m['Recall@10']:.4f}\", f\"{m['Recall@20']:.4f}\", f\"{m['NDCG@10']:.4f}\", f\"{m['NDCG@20']:.4f}\", f\"{sign}{gain:.2f}%\"])\n",
    "\n",
    "print(table)\n"
]

with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"[OK] Successfully updated {notebook_path}! (Total cells: {len(nb['cells'])})")
